### PR TITLE
Replace __resource.lua with fxmanifest.lua

### PR DESCRIPTION
**Pull request by rex2630**

### CODE REVIEW

**Comment by Blumlaut** [comment]
What exactly is the advantage of using fxmanifest over an __resource.lua? Does it improve performance? Load times?

**Comment by rex2630** [comment]
No, it doesnt improve anything. FiveM just said that __resource.lua will be deprecated with RedM release.

**Comment by Blumlaut** [comment]
if it doesnt introduce any benefits then i doubt there is a reason to change it, the last thing RDR needs is a speedometer resource.

**Comment by rex2630** [comment]
U dont get the point. __resource.lua will be deprecated for gta too after RedM release. But do whatever u want. I dont really care. I have everything with fxmanifest

**Comment by Blumlaut** [comment]
this resource is the definition of "deprecated", its nearing 3 years of age now, the only reason i recently worked on it was due to a user making a skin for it and having some issues. its fine as-is

**Pull request closed without merging**
